### ISSUE TITLE
[BUG]  rebuild switch is slowly

### ISSUE THREAD

**Issue by running-grass** [richen604/hydenix#13] opened 2024-12-09 08:21 UTC
## Bug Description

I previously had a NixOS flake configuration, but after refactoring it using Hydenix, the nixos-rebuild switch process takes a very long time, often getting stuck for several minutes at "restarting sysinit-reactivation.target." Even if no code changes are made, it still gets stuck there for several minutes.

Has anyone encountered a similar issue? Or could you provide some suggestions for troubleshooting?

## Steps to Reproduce
1. 
2. 
3. 

## System Information
<details>
<summary>System Details</summary>

``` 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-zen1, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

```bash
# Please paste the output of:
nix-shell -p nix-info --run "nix-info -m"
```
</details>

<details>
<summary>System Logs</summary>

```bash
# Please paste relevant logs from:
journalctl -b                                           # System logs
journalctl --user -b                                   # User logs
sudo systemctl status home-manager-$HOSTNAME.service   # Home-manager status
```

```  
12月 09 16:08:03 galaxy sudo[530798]:    grass : TTY=pts/3 ; PWD=/home/grass/workspace/config/nixos-config ; USER=root ; COMMAND=/run/current-system/sw/bin/nixos-rebuild switch ->
12月 09 16:08:03 galaxy sudo[530798]: pam_unix(sudo:session): session opened for user root(uid=0) by grass(uid=1000)
12月 09 16:08:11 galaxy systemd[1]: nixos-rebuild-switch-to-configuration.service: Failed to open /run/systemd/transient/nixos-rebuild-switch-to-configuration.service: No such fi>
12月 09 16:08:11 galaxy systemd[1]: Starting /nix/store/ph44jcx3ddmlwh394mh1wb7f1qigxqb1-coreutils-9.5/bin/true...
12月 09 16:08:11 galaxy systemd[1]: Started /nix/store/ph44jcx3ddmlwh394mh1wb7f1qigxqb1-coreutils-9.5/bin/true.
12月 09 16:08:11 galaxy systemd[1]: nixos-rebuild-switch-to-configuration.service: Deactivated successfully.
12月 09 16:08:12 galaxy systemd[1]: nixos-rebuild-switch-to-configuration.service: Failed to open /run/systemd/transient/nixos-rebuild-switch-to-configuration.service: No such fi>
12月 09 16:08:12 galaxy systemd[1]: Starting /nix/store/nvfynyy3973bg5pb5yhb4bz17r2vmsk5-nixos-system-galaxy-24.11.20241023.2768c7d/bin/switch-to-configuration switch...
12月 09 16:08:12 galaxy systemd[1]: Started /nix/store/nvfynyy3973bg5pb5yhb4bz17r2vmsk5-nixos-system-galaxy-24.11.20241023.2768c7d/bin/switch-to-configuration switch.
12月 09 16:08:12 galaxy nixos[530862]: switching to system configuration /nix/store/nvfynyy3973bg5pb5yhb4bz17r2vmsk5-nixos-system-galaxy-24.11.20241023.2768c7d
12月 09 16:08:12 galaxy systemd[1]: Stopped target Local File Systems.
12月 09 16:08:12 galaxy systemd[1]: Stopped target Remote File Systems.
12月 09 16:08:12 galaxy polkitd[101741]: Reloading rules
12月 09 16:08:12 galaxy polkitd[101741]: Collecting garbage unconditionally...
12月 09 16:08:12 galaxy polkitd[101741]: Loading rules from directory /etc/polkit-1/rules.d
12月 09 16:08:12 galaxy polkitd[101741]: Loading rules from directory /run/current-system/sw/share/polkit-1/rules.d
12月 09 16:08:12 galaxy polkitd[101741]: Finished loading, compiling and executing 3 rules
12月 09 16:08:12 galaxy polkitd[101741]: Reloading rules
12月 09 16:08:12 galaxy polkitd[101741]: Collecting garbage unconditionally...
12月 09 16:08:12 galaxy polkitd[101741]: Loading rules from directory /etc/polkit-1/rules.d
12月 09 16:08:12 galaxy polkitd[101741]: Loading rules from directory /run/current-system/sw/share/polkit-1/rules.d
12月 09 16:08:12 galaxy polkitd[101741]: Finished loading, compiling and executing 3 rules
12月 09 16:08:12 galaxy systemd[1]: Reload requested from client PID 530862 ('.switch-to-conf') (unit nixos-rebuild-switch-to-configuration.service)...
12月 09 16:08:12 galaxy systemd[1]: Reloading...
12月 09 16:08:12 galaxy systemd-timesyncd[858]: Network configuration changed, trying to establish connection.
12月 09 16:08:13 galaxy systemd[1]: Reloading finished in 133 ms.
12月 09 16:08:13 galaxy systemd[101871]: Reexecution requested from client PID 530981 ('switch-to-confi')...
12月 09 16:08:13 galaxy systemd[101871]: Reexecuting.
12月 09 16:08:13 galaxy systemd-xdg-autostart-generator[530985]: Exec binary '/nix/store/j738hka6czvh30y8l0qxkaqkld0529zv-electron-unwrapped-25.9.1/libexec/electron/electron' doe>
12月 09 16:08:13 galaxy systemd-xdg-autostart-generator[530985]: /home/grass/.config/autostart/bitwarden.desktop: not generating unit, executable specified in Exec= does not exis>
12月 09 16:08:13 galaxy systemd-timesyncd[858]: Contacted time server 162.159.200.1:123 (2.nixos.pool.ntp.org).
12月 09 16:08:13 galaxy dbus-daemon[102000]: [session uid=1000 pid=102000] Successfully activated service 'org.freedesktop.systemd1'
12月 09 16:08:13 galaxy systemd[101871]: Starting Run user-specific NixOS activation...
12月 09 16:08:13 galaxy systemd[101871]: Finished Run user-specific NixOS activation.
12月 09 16:08:13 galaxy systemd[1]: Stopped target Reactivate sysinit units.
12月 09 16:08:13 galaxy systemd[1]: Stopping Reactivate sysinit units...
12月 09 16:08:13 galaxy systemd[1]: Reached target Reactivate sysinit units.
12月 09 16:08:13 galaxy systemd[1]: Starting Load Kernel Module efi_pstore...
12月 09 16:08:13 galaxy systemd[1]: Starting Create SUID/SGID Wrappers...
12月 09 16:08:13 galaxy systemd[1]: File System Check on Root Device was skipped because of an unmet condition check (ConditionPathIsReadWrite=!/).
12月 09 16:08:13 galaxy systemd[1]: Reached target Local File Systems.
12月 09 16:08:13 galaxy systemd[1]: Clear Stale Hibernate Storage Info was skipped because of an unmet condition check (ConditionPathExists=/sys/firmware/efi/efivars/HibernateLoc>
12月 09 16:08:13 galaxy systemd[1]: Rebuild Journal Catalog was skipped because of an unmet condition check (ConditionNeedsUpdate=/var).
12月 09 16:08:13 galaxy systemd[1]: Early TPM SRK Setup was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
12月 09 16:08:13 galaxy systemd[1]: TPM SRK Setup was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
12月 09 16:08:13 galaxy systemd[1]: Update is Completed was skipped because no trigger condition checks were met.
12月 09 16:08:13 galaxy systemd[1]: modprobe@efi_pstore.service: Deactivated successfully.
12月 09 16:08:13 galaxy systemd[1]: Finished Load Kernel Module efi_pstore.
12月 09 16:08:13 galaxy systemd[1]: Reached target Remote File Systems.
12月 09 16:08:13 galaxy systemd[1]: Platform Persistent Storage Archival was skipped because of an unmet condition check (ConditionDirectoryNotEmpty=/sys/fs/pstore).
12月 09 16:08:13 galaxy systemd[1]: Make TPM PCR Policy was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
12月 09 16:08:13 galaxy systemd[1]: File System Check on Root Device was skipped because of an unmet condition check (ConditionPathIsReadWrite=!/).
12月 09 16:08:13 galaxy systemd[1]: suid-sgid-wrappers.service: Deactivated successfully.
12月 09 16:08:13 galaxy systemd[1]: Finished Create SUID/SGID Wrappers.
12月 09 16:08:13 galaxy systemd[1]: Starting Home Manager environment for grass...
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Starting Home Manager activation
12月 09 16:08:13 galaxy nix-daemon[1188]: accepted connection from pid 531077, user grass (trusted)
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkFilesChanged
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkLinkTargets
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating writeBoundary
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating createGpgHomedir
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating installPackages
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating dconfSettings
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating linkGeneration
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Cleaning up orphan links from /home/grass
12月 09 16:08:13 galaxy hm-activate-grass[531071]: No change so reusing latest profile generation 773
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Creating home file links in /home/grass
12月 09 16:08:14 galaxy n2n-client-start[940]: 09/Dec/2024 16:08:14 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Activating mutableFileGeneration
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Copying mutable home files for /home/grass
12月 09 16:08:30 galaxy n2n-client-start[940]: 09/Dec/2024 16:08:30 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:08:45 galaxy n2n-client-start[940]: 09/Dec/2024 16:08:45 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:09:01 galaxy n2n-client-start[940]: 09/Dec/2024 16:09:01 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:09:09 galaxy dbus-daemon[927]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requeste>
12月 09 16:09:09 galaxy systemd[1]: Starting Network Manager Script Dispatcher Service...
12月 09 16:09:09 galaxy dbus-daemon[927]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
12月 09 16:09:09 galaxy systemd[1]: Started Network Manager Script Dispatcher Service.
12月 09 16:09:17 galaxy n2n-client-start[940]: 09/Dec/2024 16:09:17 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:09:19 galaxy systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
12月 09 16:09:33 galaxy n2n-client-start[940]: 09/Dec/2024 16:09:33 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:09:49 galaxy n2n-client-start[940]: 09/Dec/2024 16:09:49 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:10:05 galaxy n2n-client-start[940]: 09/Dec/2024 16:10:05 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:10:21 galaxy n2n-client-start[940]: 09/Dec/2024 16:10:21 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:10:37 galaxy n2n-client-start[940]: 09/Dec/2024 16:10:37 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:10:51 galaxy n2n-client-start[940]: 09/Dec/2024 16:10:51 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:11:07 galaxy n2n-client-start[940]: 09/Dec/2024 16:11:07 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:11:21 galaxy n2n-client-start[940]: 09/Dec/2024 16:11:21 [edge_utils.c:1541] WARNING: supernode not responding, now trying [beacon.grass.work:37777]
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating makeStubMeta
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating hydeLink
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: -Linked to custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: [*] Using existing directory
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Hyde-cli will make /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified your clone directo>
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Successfully migrated the clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-mod>
12月 09 16:11:32 galaxy hm-activate-grass[633072]: head: cannot open '/nix/store/w19vd5f0v055dpn1jg6smqvkhhp172ng-hyde-cli/share/hyde-cli/.hyde-cli.ver' for reading: No such file>
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating importGpgKeys
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating onFilesChange
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating reloadSystemd
12月 09 16:11:32 galaxy systemd[101871]: Reload requested from client PID 633106 ('systemctl')...
12月 09 16:11:32 galaxy systemd[101871]: Reloading...
12月 09 16:11:32 galaxy systemd-xdg-autostart-generator[633110]: Exec binary '/nix/store/j738hka6czvh30y8l0qxkaqkld0529zv-electron-unwrapped-25.9.1/libexec/electron/electron' doe>
12月 09 16:11:32 galaxy systemd-xdg-autostart-generator[633110]: /home/grass/.config/autostart/bitwarden.desktop: not generating unit, executable specified in Exec= does not exis>
12月 09 16:11:32 galaxy systemd[101871]: Reloading finished in 98 ms.
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating runMuInit
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating swwwallCache
12月 09 16:11:32 galaxy hm-activate-grass[633201]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633203]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [180B blob data]
12月 09 16:11:33 galaxy hm-activate-grass[633207]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633209]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [4.6K blob data]
12月 09 16:11:33 galaxy hm-activate-grass[531071]: Activating setTheme
12月 09 16:11:33 galaxy hm-activate-grass[633246]: :: applying theme :: "Catppuccin Mocha"
12月 09 16:11:33 galaxy hm-activate-grass[633351]: :: applying wall :: "/home/grass/.config/hyde/themes/Catppuccin Mocha/wallpapers/apex_octane.jpg"
12月 09 16:11:33 galaxy systemd[1]: home-manager-grass.service: Deactivated successfully.
12月 09 16:11:33 galaxy systemd[1]: Finished Home Manager environment for grass.
12月 09 16:11:33 galaxy systemd[1]: home-manager-grass.service: Consumed 3min 33.444s CPU time, 377.6M memory peak.
12月 09 16:11:33 galaxy nixos[530862]: finished switching to system configuration /nix/store/nvfynyy3973bg5pb5yhb4bz17r2vmsk5-nixos-system-galaxy-24.11.20241023.2768c7d
12月 09 16:11:33 galaxy systemd[1]: nixos-rebuild-switch-to-configuration.service: Deactivated successfully.
12月 09 16:11:33 galaxy systemd[1]: nixos-rebuild-switch-to-configuration.service: Consumed 465ms CPU time, 171.4M memory peak.
12月 09 16:11:33 galaxy sudo[530798]: pam_unix(sudo:session): session closed for user root

```  

```  
12月 09 16:08:13 galaxy systemd[101871]: Reexecution requested from client PID 530981 ('switch-to-confi')...
12月 09 16:08:13 galaxy systemd[101871]: Reexecuting.
12月 09 16:08:13 galaxy systemd-xdg-autostart-generator[530985]: Exec binary '/nix/store/j738hka6czvh30y8l0qxkaqkld0529zv-electron-unwrapped-25.9.1/libexec/electron/electron' doe>
12月 09 16:08:13 galaxy systemd-xdg-autostart-generator[530985]: /home/grass/.config/autostart/bitwarden.desktop: not generating unit, executable specified in Exec= does not exis>
12月 09 16:08:13 galaxy dbus-daemon[102000]: [session uid=1000 pid=102000] Successfully activated service 'org.freedesktop.systemd1'
12月 09 16:08:13 galaxy systemd[101871]: Starting Run user-specific NixOS activation...
12月 09 16:08:13 galaxy systemd[101871]: Finished Run user-specific NixOS activation.
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Starting Home Manager activation
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkFilesChanged
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkLinkTargets
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating writeBoundary
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating createGpgHomedir
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating installPackages
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating dconfSettings
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating linkGeneration
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Cleaning up orphan links from /home/grass
12月 09 16:08:13 galaxy hm-activate-grass[531071]: No change so reusing latest profile generation 773
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Creating home file links in /home/grass
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Activating mutableFileGeneration
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Copying mutable home files for /home/grass
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating makeStubMeta
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating hydeLink
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: -Linked to custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: [*] Using existing directory
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Hyde-cli will make /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified your clone directo>
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Successfully migrated the clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-mod>
12月 09 16:11:32 galaxy hm-activate-grass[633072]: head: cannot open '/nix/store/w19vd5f0v055dpn1jg6smqvkhhp172ng-hyde-cli/share/hyde-cli/.hyde-cli.ver' for reading: No such file>
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating importGpgKeys
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating onFilesChange
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating reloadSystemd
12月 09 16:11:32 galaxy systemd[101871]: Reload requested from client PID 633106 ('systemctl')...
12月 09 16:11:32 galaxy systemd[101871]: Reloading...
12月 09 16:11:32 galaxy systemd-xdg-autostart-generator[633110]: Exec binary '/nix/store/j738hka6czvh30y8l0qxkaqkld0529zv-electron-unwrapped-25.9.1/libexec/electron/electron' doe>
12月 09 16:11:32 galaxy systemd-xdg-autostart-generator[633110]: /home/grass/.config/autostart/bitwarden.desktop: not generating unit, executable specified in Exec= does not exis>
12月 09 16:11:32 galaxy systemd[101871]: Reloading finished in 98 ms.
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating runMuInit
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating swwwallCache
12月 09 16:11:32 galaxy hm-activate-grass[633201]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633203]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [180B blob data]
12月 09 16:11:33 galaxy hm-activate-grass[633207]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633209]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [4.6K blob data]
12月 09 16:11:33 galaxy hm-activate-grass[531071]: Activating setTheme
12月 09 16:11:33 galaxy hm-activate-grass[633246]: :: applying theme :: "Catppuccin Mocha"
12月 09 16:11:33 galaxy hm-activate-grass[633351]: :: applying wall :: "/home/grass/.config/hyde/themes/Catppuccin Mocha/wallpapers/apex_octane.jpg"
12月 09 16:11:33 galaxy sudo[530798]: pam_unix(sudo:session): session closed for user root

```  

```  
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Starting Home Manager activation
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkFilesChanged
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating checkLinkTargets
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating writeBoundary
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating createGpgHomedir
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating installPackages
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating dconfSettings
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Activating linkGeneration
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Cleaning up orphan links from /home/grass
12月 09 16:08:13 galaxy hm-activate-grass[531071]: No change so reusing latest profile generation 773
12月 09 16:08:13 galaxy hm-activate-grass[531071]: Creating home file links in /home/grass
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Activating mutableFileGeneration
12月 09 16:08:15 galaxy hm-activate-grass[531071]: Copying mutable home files for /home/grass
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating makeStubMeta
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating hydeLink
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: -Linked to custom clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified
12月 09 16:11:32 galaxy hm-activate-grass[633044]: [*] Using existing directory
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Hyde-cli will make /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-modified your clone directo>
12月 09 16:11:32 galaxy hm-activate-grass[633044]: Successfully migrated the clone directory: /home/grass/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyprdots-mod>
12月 09 16:11:32 galaxy hm-activate-grass[633072]: head: cannot open '/nix/store/w19vd5f0v055dpn1jg6smqvkhhp172ng-hyde-cli/share/hyde-cli/.hyde-cli.ver' for reading: No such file>
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating importGpgKeys
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating onFilesChange
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating reloadSystemd
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating runMuInit
12月 09 16:11:32 galaxy hm-activate-grass[531071]: Activating swwwallCache
12月 09 16:11:32 galaxy hm-activate-grass[633201]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633203]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [180B blob data]
12月 09 16:11:33 galaxy hm-activate-grass[633207]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633209]: sh: 行 1: /dev/tty: No such device or address
12月 09 16:11:33 galaxy hm-activate-grass[633161]: [4.6K blob data]
12月 09 16:11:33 galaxy hm-activate-grass[531071]: Activating setTheme
12月 09 16:11:33 galaxy hm-activate-grass[633246]: :: applying theme :: "Catppuccin Mocha"
12月 09 16:11:33 galaxy hm-activate-grass[633351]: :: applying wall :: "/home/grass/.config/hyde/themes/Catppuccin Mocha/wallpapers/apex_octane.jpg"
12月 09 16:11:33 galaxy systemd[1]: home-manager-grass.service: Deactivated successfully.
``` 

</details>

## Environment
- [] NixOS VM
- [x] Templated Flake
- [ ] Cross-distro VM (specify: Arch/Fedora)
- [ ] Other (please specify)

## Checklist
- [x] I have checked for existing issues
- [x] I have included all relevant system information
- [x] I have included relevant logs
- [ ] I have provided my configuration

**Comment by richen604** [comment] 2024-12-12 00:30
@running-grass ive taken a look at a few similar issues https://github.com/NixOS/nixpkgs/issues/313696 https://github.com/NixOS/nixpkgs/issues/353450
do you have any failed services? any custom configurations in the template flake?

**Comment by richen604** [comment] 2024-12-18 00:48
closing as i suspect this is a custom config issue, not a bug in hydenix
> I previously had a NixOS flake configuration, but after refactoring it using Hydenix,
use a minimal nixos installation for hydenix for best support

**Closed by richen604** 2024-12-18 00:48 UTC
Labels: bug
